/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddIcon: typeof import('./src/components/icons/AddIcon.vue')['default']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    HomeIcon: typeof import('./src/components/icons/HomeIcon.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserIcon: typeof import('./src/components/icons/UserIcon.vue')['default']
  }
}
